from typing import Final

DEFAULT_TEMPLATE: Final = "{uploader.name} - {title}"
DEFAULT_WORKERS: Final = 5
DEFAULT_SEGMENT_WORKERS: Final = 8
DEFAULT_RETRIES: Final = 3
DEFAULT_IMPERSONATE_TARGET: Final = "chrome"
DEFAULT_VIDEO_CONTAINER: Final = "MP4"
DEFAULT_AUDIO_CONTAINER: Final = "M4A"
