import re
from pathlib import Path
from typing import Annotated, Any, Self

import remora
from remora.models._base import BaseList, EnsureBool, EnsureNone, RemoraModel
from remora.models.types import StrPath

__all__ = ["Cookie", "CookieList"]
_NETSCAPE_HEADER = re.compile("#( Netscape)? HTTP Cookie File")


class Cookie(RemoraModel):
    name: str
    value: str
    domain: str
    path: str = "/"
    secure: Annotated[bool, EnsureBool] = False
    expires: Annotated[int | None, EnsureNone] = None


class CookieList(BaseList[Cookie]):
    @classmethod
    def from_file(cls, file_path: StrPath) -> Self:
        file_path = Path(file_path)
        content = file_path.read_text()
        extension = file_path.suffix[1:]

        match extension:
            case "txt":
                return cls.from_netscape_cookies(content)
            case "json":
                return cls.from_json(content)
        raise ValueError("Unable to determine cookies file format")

    @classmethod
    def from_json(cls, data: str | bytes | bytearray) -> Self:
        return cls.model_validate_json(data)

    def to_json(self) -> str:
        return self.model_dump_json()

    @classmethod
    def from_netscape_cookies(cls, data: str) -> Self:
        lines = data.splitlines()
        cookies = []

        # Keys in the order required by Netscape format
        keys = [
            "domain",
            "include_subdomains",
            "path",
            "secure",
            "expires",
            "name",
            "value",
        ]

        # Check that the content have Netscape header
        if not _NETSCAPE_HEADER.match(lines[0]):
            raise ValueError("Content doesn't look like Netscape cookies format")

        for line in lines:
            line = line.strip()

            if not line:
                continue

            # Handle the standard Netscape HttpOnly prefix
            if line.startswith("#HttpOnly_"):
                line = line[10:]
            elif line.startswith("#"):
                continue

            # Netscape cookies are strictly tab-separated
            parts = line.split("\t")

            # zip() will safely map only as many parts as are available.
            cookie: dict[str, Any] = dict(zip(keys, parts))

            # Fallback for missing "value" field
            if not cookie.get("value"):
                cookie["value"] = ""

            # Pre-process specific fields
            if secure := cookie.get("secure"):
                cookie["secure"] = secure.upper() == "TRUE"

            # In Netscape format, an expiration of 0 typically means a session cookie
            if (expires := cookie.get("expires")) and not (expires or expires == "0"):
                cookie["expires"] = None

            cookies.append(cookie)
        return cls.model_validate(cookies)

    def to_netscape_cookies(self) -> str:
        lines = [
            "# Netscape HTTP Cookie File",
            f"# This file is generated by {remora.__name__}.  Do not edit.",
            "",
        ]

        for cookie in self:
            domain = cookie.domain
            include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
            path = cookie.path
            secure = "TRUE" if cookie.secure else "FALSE"
            expires = str(cookie.expires if cookie.expires else "0")
            name = cookie.name
            value = cookie.value

            lines.append(
                f"{domain}\t{include_subdomains}\t{path}\t{secure}\t{expires}\t{name}\t{value}"
            )

        return "\n".join(lines) + "\n"

    @classmethod
    def from_cookie_header(cls, data: str) -> Self:
        from remora._ydl.cookies import LenientSimpleCookie

        parsed = LenientSimpleCookie(data)
        return cls(
            {
                "name": name,
                "value": morsel.value,
                "domain": morsel["domain"],
                "path": morsel["path"],
                "secure": morsel["secure"],
                "expires": morsel["expires"],
            }
            for name, morsel in parsed.items()
        )

    def to_cookie_header(self) -> str:
        from remora._ydl.cookies import LenientSimpleCookie

        encoder = LenientSimpleCookie()
        values = []

        for c in self:
            _, encoded_value = encoder.value_encode(c.value)

            values.append(f"{c.name}={encoded_value}")
            values.append(f"Domain={c.domain}")
            values.append(f"Path={c.path}")
            if c.secure:
                values.append("Secure")
            values.append(f"Expires={c.expires}")
        return "; ".join(values)
