from __future__ import annotations

from typing import Annotated, Generic, Literal, Self

from pydantic import Field, HttpUrl
from typing_extensions import TypeVar, override

from remora.models._base import BaseList, Impersonate, RemoraModel, YDLSerializable
from remora.models.metadata._base import Metadata


class SubtitleRequestContext(RemoraModel):
    headers: Annotated[dict | None, Field(alias="http_headers")] = None
    impersonate: Impersonate = False


class _BaseSubtitle(Metadata, YDLSerializable):
    name: str = ""
    language: str
    extension: Annotated[str, Field(alias="ext")]
    autogenerated: bool = False
    request_context: SubtitleRequestContext = SubtitleRequestContext()

    @override
    def _to_ydl_dict(self) -> dict[str, list[dict[str, str]]]:
        entry = self.model_dump(
            by_alias=True,
            mode="json",
            exclude={"type", "language"},
        )
        data = {self.language: [entry]}
        return data


class ExternalSubtitle(_BaseSubtitle):
    type: Literal["external"] = "external"
    url: HttpUrl


class InlineSubtitle(_BaseSubtitle):
    type: Literal["inline"] = "inline"
    content: Annotated[str, Field(alias="data")]


Subtitle = ExternalSubtitle | InlineSubtitle


_T = TypeVar("_T", bound=Subtitle, default=Subtitle)


class SubtitleList(YDLSerializable, BaseList[_T], Generic[_T]):
    def get_languages(self) -> set[str]:
        """Return all unique language codes available across all subtitles."""
        return {s.language for s in self.root}

    def externals(self) -> SubtitleList[ExternalSubtitle]:
        """Subtitles hosted on a URL."""
        return SubtitleList[ExternalSubtitle](
            (item for item in self if isinstance(item, ExternalSubtitle)),
        )

    def inlines(self) -> SubtitleList[InlineSubtitle]:
        """Subtitles provided directly as string content."""
        return SubtitleList[InlineSubtitle](  # type: ignore
            (item for item in self if isinstance(item, InlineSubtitle)),
        )

    def filter(
        self,
        language: str | None = None,
        extension: str | None = None,
        autogenerated: bool | None = None,
    ) -> Self:
        """Filter subtitles by options."""

        items = (s for s in self.root)

        if language:
            items = (s for s in items if s.language.startswith(language))
        if extension:
            items = (s for s in items if s.extension == extension)
        if autogenerated:
            items = (s for s in items if s.autogenerated)

        return self.__class__(items)

    @classmethod
    def _from_ydl_dict(cls, data: dict) -> Self:
        subtitles: dict[str, list[dict[str, str]]] = data.pop("subtitles", {})
        automatic_captions: dict[str, list[dict[str, str]]] = data.pop(
            "automatic_captions", {}
        )
        flat_subtitles: list[dict] = []

        def transform(entry: dict, autogenerated: bool = False):
            sub_type = "external" if ("url" in entry) else "embedded"
            return {
                **entry,
                "type": sub_type,
                "language": lang,
                "request_context": entry,
                "autogenerated": autogenerated,
            }

        for lang, sub in subtitles.items():
            for value in sub:
                flat_subtitles.append(transform(value))

        for lang, sub in automatic_captions.items():
            for value in sub:
                flat_subtitles.append(transform(value, autogenerated=True))

        return cls(flat_subtitles)

    @override
    def _to_ydl_dict(self) -> dict:
        """Convert back into the nested yt-dlp dictionary format:"""

        data = {}

        for subtitle in self.root:
            entry = subtitle._to_ydl_dict()

            for lang, sub in entry.items():
                for value in sub:
                    if not data.get(lang):
                        data[lang] = []
                    data[lang].append(value)

        return data
