from __future__ import annotations

from typing import Annotated, Generic, Literal, Self

from pydantic import AnyUrl, Field
from typing_extensions import TypeVar, override

from remora.models._base import (
    BaseList,
    FilterValue,
    Impersonate,
    RemoraModel,
    YDLSerializable,
    to_tuple,
)
from remora.models.metadata._base import Metadata


class SubtitleRequestContext(RemoraModel):
    headers: Annotated[dict | None, Field(alias="http_headers")] = None
    impersonate: Impersonate = False


class _BaseSubtitle(Metadata, YDLSerializable):
    name: str = ""
    language: str
    extension: Annotated[str, Field(alias="ext")]
    autogenerated: bool = False
    request_context: SubtitleRequestContext = SubtitleRequestContext()

    @override
    def _to_ydl_dict(self) -> dict[str, list[dict[str, str]]]:
        entry = self.model_dump(
            by_alias=True,
            mode="json",
            exclude={"type", "language"},
        )
        data = {self.language: [entry]}
        return data


class ExternalSubtitle(_BaseSubtitle):
    type: Literal["external"] = "external"
    url: AnyUrl


class InlineSubtitle(_BaseSubtitle):
    type: Literal["inline"] = "inline"
    content: Annotated[str, Field(alias="data")]


Subtitle = ExternalSubtitle | InlineSubtitle


_T = TypeVar("_T", bound=Subtitle, default=Subtitle)


class SubtitleList(YDLSerializable, BaseList[_T], Generic[_T]):
    def get_languages(self) -> set[str]:
        """Return all unique language codes available across all subtitles."""
        return {s.language for s in self.root}

    def externals(self) -> SubtitleList[ExternalSubtitle]:
        """Subtitles hosted on a URL."""
        return SubtitleList[ExternalSubtitle](
            (item for item in self if isinstance(item, ExternalSubtitle)),
        )

    def inlines(self) -> SubtitleList[InlineSubtitle]:
        """Subtitles provided directly as string content."""
        return SubtitleList[InlineSubtitle](  # type: ignore
            (item for item in self if isinstance(item, InlineSubtitle)),
        )

    def filter(
        self,
        language: FilterValue[str] = None,
        extension: FilterValue[str] = None,
        autogenerated: bool | None = None,
    ) -> Self:
        """Filter subtitles by options."""

        items = (s for s in self.root)

        if language:
            values: tuple[str, ...] = to_tuple(language)  # ty: ignore[invalid-assignment]
            items = (s for s in items if s.language.startswith(values))
        if extension:
            values: tuple[str, ...] = to_tuple(extension)  # ty: ignore[invalid-assignment]
            items = (s for s in items if s.extension in values)
        if autogenerated:
            items = (s for s in items if s.autogenerated == autogenerated)

        return self.__class__(items)

    def sorted_by(
        self,
        attribute: Literal["best", "language", "extension", "autogenerated"],
        reverse: bool = True,
    ) -> Self:
        """Sort by `Subtitle` attribute."""

        if attribute == "best":
            filter = lambda s: not s.autogenerated
        else:
            filter = lambda s: getattr(s, attribute)

        return self.__class__(
            sorted(
                self.root,
                key=filter,
                reverse=reverse,
            )
        )

    @classmethod
    def _from_ydl_dict(cls, data: dict) -> Self:
        subtitles: dict[str, list[dict[str, str]]] = data.get("subtitles", {})
        automatic_captions: dict[str, list[dict[str, str]]] = data.get(
            "automatic_captions", {}
        )
        flat_subtitles: list[dict] = []

        def transform(entry: dict, autogenerated: bool = False):
            sub_type = "external" if ("url" in entry) else "embedded"
            return {
                **entry,
                "type": sub_type,
                "language": lang,
                "request_context": entry,
                "autogenerated": autogenerated,
            }

        for lang, sub in subtitles.items():
            for value in sub:
                flat_subtitles.append(transform(value))

        for lang, sub in automatic_captions.items():
            for value in sub:
                flat_subtitles.append(transform(value, autogenerated=True))

        return cls(flat_subtitles)
