import pytest

from remora.models.metadata.subtitle import (
    ExternalSubtitle,
    InlineSubtitle,
    SubtitleList,
)


@pytest.fixture
def subs() -> SubtitleList:
    URL = "http://example.com/subtitle"

    return SubtitleList(
        [
            ExternalSubtitle(
                name="English",
                language="en",
                extension="vtt",
                url=URL,
            ),
            ExternalSubtitle(
                name="Spanish",
                language="es",
                extension="vtt",
                url=URL,
            ),
            ExternalSubtitle(
                name="Spanish",
                language="es-419",
                extension="srt",
                url=URL,
            ),
            ExternalSubtitle(
                name="French",
                language=" fr",
                extension="srt",
                url=URL,
                autogenerated=True,
            ),
            InlineSubtitle(
                name="Lyrics",
                language="lyrics",
                extension="lrc",
                content="...",
            ),
        ]
    )


# Filters: Type
async def test_externals(subs: SubtitleList):
    assert len(subs.externals()) > 0


async def test_inlines(subs: SubtitleList):
    assert len(subs.inlines()) > 0


async def test_languages(subs: SubtitleList):
    assert all(key in subs.get_languages() for key in ("en", "es-419"))


# Filters: General
async def test_filter_autogenerated(subs: SubtitleList):
    results = subs.filter(autogenerated=True)
    assert len(results) == 1


async def test_filter_languages(subs: SubtitleList):
    results = subs.filter(language="es")
    assert all(s.language.startswith("es") for s in results)


async def test_filter_extension(subs: SubtitleList):
    results = subs.filter(extension="vtt")
    assert all(s.extension == "vtt" for s in results)


# Sorter
async def test_sorted_autogenerated(subs: SubtitleList):
    results = subs.sorted_by("autogenerated", False)
    assert not results[0].autogenerated
