from typing import Final

DEFAULT_TEMPLATE: Final = "{uploader.name} - {title}"
DEFAULT_TEMPLATE_MISSING: Final = "NA"

DEFAULT_MEDIA_CONCURRENCY: Final = 5
DEFAULT_SEGMENT_CONCURRENCY: Final = 8
DEFAULT_POSTPROCESS_CONCURRENCY: Final = 1

DEFAULT_IMPERSONATE_TARGET: Final = "chrome"
DEFAULT_STREAM_LANGUAGE: Final = "en"
DEFAULT_RETRIES: Final = 3

DEFAULT_VIDEO_CONTAINER: Final = "mkv"
DEFAULT_AUDIO_CONTAINER: Final = "mka"
