"""Typer-style help formatter for cyclopts.

Transforms cyclopts' default help panels into the classic Typer rich layout:

- Option/flag names are comma-joined on a single line (``--type, -t``) instead of
  being split across lines with an uppercase metavar prefix.
- Internal ``--empty-*`` flags generated by cyclopts are hidden.
- Long option names wrap with a hanging indent rather than folding onto new rows.
"""

from enum import StrEnum

from cyclopts.help import (
    ColumnSpec,
    DefaultFormatter,
    HelpEntry,
    Renderer,
)
from cyclopts.help.specs import AsteriskColumn, DescriptionColumn, PanelSpec


class HelpStyle(StrEnum):
    """Rich markup style for each help entry variation."""

    POSITIVE = "bold cyan"  # command names and positive flags (--output, --convert)
    POSITIVE_SHORTS = "bold green"  # positive alias flags (-o, -f)
    NEGATIVE = "bold magenta"  # negated boolean flags (--force)
    NEGATIVE_SHORTS = "bold green"  # negated boolean flags (-f)
    METAVAR = "bold yellow"  # value placeholders (<OUTPUT>)

    def apply(self, text: str) -> str:
        """Wrap `text` in this style's markup."""
        return f"[{self}]{text}[/]"


class _NameRenderer(Renderer):
    def __call__(self, entry: HelpEntry):
        self.entry = entry
        return self.name

    @property
    def name(self) -> str:
        """Render option/command names with colors."""
        # Command entries carry no flags and no value type: every name is the
        # command itself (e.g. "download", "extract").
        if not self.entry.type and not any(
            name.startswith("-") for name in self.entry.all_options
        ):
            return " ".join(self.styled_all_options)

        # Format
        options = self.styled_all_options
        text = " ".join(options)

        if metavar := self.metavar:
            text = f"{text} {metavar}"

        return text

    @property
    def metavar(self) -> str | None:
        """Styled value placeholder (`<OUTPUT>`), or `None` for bare switches."""
        if self.entry.type is bool:
            return None

        value_name = next(
            (
                name
                for name in self.entry.all_options
                if name and not name.startswith("-")
            ),
            None,
        )
        if not value_name:
            return None

        return HelpStyle.METAVAR.apply(f"<{value_name.replace('-', '_')}>")

    @property
    def styled_all_options(self) -> list[str]:
        return [
            *self.styled_positive_names,
            *self.styled_positive_shorts,
            *self.styled_negative_names,
            *self.styled_negative_shorts,
        ]

    @property
    def styled_positive_names(self) -> list[str]:
        names = list(self.entry.positive_names)

        metavar = self.entry.positive_names[0]
        if metavar.isupper():
            names.remove(metavar)

        return [HelpStyle.POSITIVE.apply(o) for o in names]

    @property
    def styled_positive_shorts(self) -> list[str]:
        return [HelpStyle.POSITIVE_SHORTS.apply(o) for o in self.entry.positive_shorts]

    @property
    def styled_negative_names(self) -> list[str]:
        return [HelpStyle.NEGATIVE.apply(o) for o in self.entry.negative_names]

    @property
    def styled_negative_shorts(self) -> list[str]:
        return [HelpStyle.NEGATIVE_SHORTS.apply(o) for o in self.entry.negative_shorts]


def _columns_builder(console, options, entries: list[HelpEntry]):
    name_column = ColumnSpec(renderer=_NameRenderer())

    # Add the required-marker column only when an entry needs it.
    if any(entry.required for entry in entries):
        return (AsteriskColumn, name_column, DescriptionColumn)

    return (name_column, DescriptionColumn)


AppFormatter = DefaultFormatter(
    column_specs=_columns_builder,
    panel_spec=PanelSpec(border_style="dim"),
)
