"""Typer-style help formatter for cyclopts.

Transforms cyclopts' default help panels into the classic Typer rich layout:

- Option/flag names are comma-joined on a single line (``--type, -t``) instead of
  being split across lines with an uppercase metavar prefix.
- Internal ``--empty-*`` flags generated by cyclopts are hidden.
- Long option names wrap with a hanging indent rather than folding onto new rows.
"""

import math
import textwrap
from typing import TYPE_CHECKING

from cyclopts.help import (
    ColumnSpec,
    DefaultFormatter,
    HelpEntry,
)
from cyclopts.help.specs import AsteriskColumn, DescriptionColumn

if TYPE_CHECKING:
    from rich.console import Console, ConsoleOptions


class TyperNameRenderer:
    """Render option/command names Typer-style.

    Commas-joins the option aliases and drops the cyclopts-only ``--empty-*``
    flags and the uppercase metavar prefix.
    """

    def __init__(self, max_width: int | None = None) -> None:
        self.max_width = max_width

    def __call__(self, entry: HelpEntry) -> str:
        flags = [
            name
            for name in entry.all_options
            if name.startswith("-") and not name.startswith("--empty-")
        ]

        if not flags:
            # Pure positional argument, no flag aliases: keep the display name.
            flags = [
                name
                for name in entry.all_options
                if name and not name.startswith("--empty-")
            ][:1]

        text = ", ".join(flags)

        if self.max_width is None:
            return text

        return "\n".join(
            textwrap.wrap(
                text,
                self.max_width,
                subsequent_indent="  ",
                break_on_hyphens=False,
                tabsize=4,
            )
        )


def typer_columns(
    console: "Console",
    options: "ConsoleOptions",
    entries: list[HelpEntry],
) -> tuple[ColumnSpec, ...]:
    """Build the columns used by the Typer-style help panels."""
    max_width = math.ceil(console.width * 0.4)
    name_column = ColumnSpec(
        renderer=TyperNameRenderer(max_width=max_width),
        header="Option",
        justify="left",
        style="bold cyan",
        max_width=max_width,
    )

    if any(entry.required for entry in entries):
        return (AsteriskColumn, name_column, DescriptionColumn)
    return (name_column, DescriptionColumn)


TyperFormatter = DefaultFormatter(column_specs=typer_columns)
