"""Typer-style help formatter for cyclopts.

Transforms cyclopts' default help panels into the classic Typer rich layout:

- Option/flag names are comma-joined on a single line (``--type, -t``) instead of
  being split across lines with an uppercase metavar prefix.
- Internal ``--empty-*`` flags generated by cyclopts are hidden.
- Long option names wrap with a hanging indent rather than folding onto new rows.
"""

from cyclopts.help import (
    ColumnSpec,
    DefaultFormatter,
    HelpEntry,
)
from cyclopts.help.specs import AsteriskColumn, DescriptionColumn


class Style:
    COMMAND = "bold cyan"
    SHORT_COMMAND = "deep_pink3"
    METAVAR = "orange1"


def _names_renderer(entry: HelpEntry) -> str:
    """Render option/command names Typer-style.

    Commas-joins the option aliases and drops the cyclopts-only ``--empty-*``
    flags and the uppercase metavar prefix.
    """

    # Command entries carry no flags and no value type: every name is the
    # command itself (e.g. "download", "extract"), display them joined.
    if entry.type is None and not any(
        name.startswith("-") for name in entry.all_options
    ):
        return ", ".join(name for name in entry.all_options if name)

    flags = [
        name
        for name in entry.all_options
        if name.startswith("-") and not name.startswith("--empty-")
    ]

    # Booleans are bare switches, they take no value, so no metavar.
    is_bool = entry.type is bool or not flags
    metavar = (
        next(
            (name for name in entry.all_options if name and not name.startswith("-")),
            None,
        )
        if not is_bool
        else None
    )
    if metavar:
        metavar = metavar.replace("-", "_")

    def style_flag(name: str, is_negative: bool = False) -> str:
        """Highlight short aliases (`-o`) and negative boolean flags (`--force`)."""
        if is_negative:
            return f"[{Style.SHORT_COMMAND}]{name}[/]"
        return name

    negatives = (
        set(entry.negative_names) | set(entry.negative_shorts) | set(entry.shorts)
    )
    text = " ".join(style_flag(name, name in negatives) for name in flags)

    if flags and metavar:
        text = f"{text} [{Style.METAVAR}]<{metavar}>[/]"
    elif not flags:
        # Pure positional with no generated flags: show the placeholder.
        text = metavar or ""

    return text


def _columns_builder(console, options, entries: list[HelpEntry]):
    """Drop the required-marker column unless an entry actually needs it.

    `AsteriskColumn` is a fixed `width=1` cell that renders as a blank gap on
    every row, so it is only kept when at least one entry is required.
    """
    name_column = ColumnSpec(renderer=_names_renderer, style=Style.COMMAND)

    if any(entry.required for entry in entries):
        return (AsteriskColumn, name_column, DescriptionColumn)
    return (name_column, DescriptionColumn)


AppFormatter = DefaultFormatter(
    column_specs=_columns_builder,
)
